name : telemedecine
channels :
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - plotly
  - requests
  - python-dotenv
  - pydantic
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - ipykernel
  - scipy